### ISSUE TITLE
Tendenzpfeile fehlen

### ISSUE THREAD

**Issue by jnhllTM4** [Keyes/its-beds-widget#11]
Bei mir sind die Tendenzpfeile nicht mehr sichtbar. Woran kann das liegen?

![21FBD7CE-9B75-44C1-9F99-7CE0D53A343B](https://user-images.githubusercontent.com/73250188/105573987-baac5880-5d61-11eb-9f38-545eec14b54d.jpeg)

**Comment by Keyes** [comment]
Ich habe gerade einen Bug in der API gefixed der dadurch entstanden ist, dass das Intensivregister seine Daten jetzt in einem anderen Format bereitstellt. Ggf. wird dieser Fehler dadurch auch behoben.

**Comment by Keyes** [comment]
Gefixed und released in #13
