### ISSUE TITLE
Error on line 288:34: TypeError: undefined is not an object (evaluating 'newData.updated.substr')

### ISSUE THREAD

**Issue by rafaelmaeuer** [Keyes/its-beds-widget#12]
Maybe some date object is missing here? Have there been an update to the API?

**Comment by Keyes** [comment]
I can confirm that something is wrong right now, but I didn’t change something neither in the widget nor in the backend, which confuses me a lot. Maybe scriptable changed something? Although I did not receive an update recently... will continue to investigate

**Comment by Keyes** [comment]
The API of "Intensivregister" was changed in which the timestamp of the latest update was changed - fixed this now. The widget should now work again as expected
