### ISSUE TITLE
No data available

### ISSUE THREAD

**Issue by ProfMertes** [Keyes/its-beds-widget#4]
It seems that the current version (dev and stable) of the script does not deliver any data inside the widget. This was tested on 3 different iPhones (iOS 14.1, with both options extended/simple and with several states as Parameters). No errors in the Log window.
<img width="157" alt="scriptable_icon_not_working" src="https://user-images.githubusercontent.com/20865388/97459770-69e0bb80-193c-11eb-8128-72bc6866f94a.png">

**Comment by Keyes** [comment]
Hi @ProfMertes, you need to press-hold the widget, tap "Edit Scriptable" and select the widget you've created with the code from the readme.

**Comment by ProfMertes** [comment]
Thanks for the hint, but this step is clear for me. I have already several scripts running with Scriptable. I have step through every single line of code and can't find the reason. Even the basis of the country-wide number of beds delivers the data correctly (https://intensiv-widget.juliankern.com/beds). Any other other hints why this script is not working for me on different devices?

**Comment by Keyes** [comment]
Unfortunately not :( I have two other reports of not working devices, but for now no lead what actually (not) happens there :/ my first guess was that the network/provider or a content-blocker is blocking the API or script requests, but you say that's working for you...

**Comment by ProfMertes** [comment]
Just to be clear. In the Paramter window from the widget there is only the state code (HH, BW, etc.) to be filled in? If not, can you provide any screenshots or example data of a working Parameter set?

**Comment by Keyes** [comment]
Exactly: Just the state short code - or leave it empty to let the widget detect your location

**Comment by ProfMertes** [comment]
Can't explain it, but since today afternoon it works perfectly. Thanks for the script!

**Comment by Keyes** [comment]
Glad to hear! I rewrote the whole backend yesterday, and added a couple of fixes today to it and the widget :)

**Comment by ProfMertes** [comment]
Great to hear that you rewrote the whole backend and fixed some problems. It seems that was very valuable. Keep up the good work!
