### ISSUE TITLE
Icon Farbe und %-Angabe

### ISSUE THREAD

**Issue by Eeewald85** [Keyes/its-beds-widget#8]
Hey,

seit das „Bett“ Icon gegen ein (weißes) Stethoskop getauscht wurde, wird dieses Icon nur noch im Darkmode angezeigt. Im hellen Modus, wenn der Hintergrund des Widgets weiß ist, sieht man das Icon leider nicht mehr. Lässt sich da irgendwas dran drehen? ;-)

Die %-Angabe zeigt ja die belegten ITS Betten an. Aber das Widget nennt sich ja „freie ITS Betten“. Wäre es nicht sinnvoll, die %-Angabe passend dazu anzuzeigen? Also die freien Betten anzuzeigen statt die belegten? 

Viele Grüße

**Comment by Keyes** [comment]
Das Icon-Problem wurde mit [#7](https://github.com/Keyes/its-beds-widget/pull/7) gefixed, und sollte bei dem nächsten reload des Widgets korrekt angezeigt :) 

Zum zweiten Punkt: das Widget zeigt wie im Titel benannt die Quote der freien Betten an, wie man im Extended-Layout auch nachvollziehen kann :)
